
# **Natural Language Processing (NLP) Pipeline**

An NLP pipeline is a sequence of preprocessing and modeling steps used to convert raw text into meaningful numerical features that machine learning models can understand.

Typical NLP workflow:

1. Text Cleaning
2. Tokenization
3. Stopword Removal
4. Stemming / Lemmatization
5. Text Vectorization (Bag of Words / TF-IDF)
6. Model Training
7. Evaluation

Pipelines help ensure that **all preprocessing steps are applied consistently during training and prediction**.


## **1. Import Required Libraries**

In [1]:

import pandas as pd
import numpy as np
import re

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score



## **2. Create Sample Text Dataset**
In NLP tasks datasets usually contain:
- A text column
- A target label


In [2]:

data = pd.DataFrame({
    "text":[
        "I love machine learning",
        "NLP is very interesting",
        "I hate spam emails",
        "Machine learning is powerful",
        "Spam messages are annoying"
    ],
    "label":[1,1,0,1,0]
})

data


,text,label
0,I love machine learning,1
1,NLP is very interesting,1
2,I hate spam emails,0
3,Machine learning is powerful,1
4,Spam messages are annoying,0



## **3. Basic Text Cleaning**

Common cleaning steps:
- Convert to lowercase
- Remove punctuation
- Remove numbers


In [3]:

def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z ]", "", text)
    return text

data["clean_text"] = data["text"].apply(clean_text)

data


,text,label,clean_text
0,I love machine learning,1,i love machine learning
1,NLP is very interesting,1,nlp is very interesting
2,I hate spam emails,0,i hate spam emails
3,Machine learning is powerful,1,machine learning is powerful
4,Spam messages are annoying,0,spam messages are annoying


## **4. Train Test Split**

In [4]:

X = data["clean_text"]
y = data["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)



## **5. Bag of Words (CountVectorizer)**

Bag of Words converts text into numerical vectors based on word frequency.


In [5]:

vectorizer = CountVectorizer()

X_vectorized = vectorizer.fit_transform(X_train)

print(vectorizer.get_feature_names_out())
print(X_vectorized.toarray())


['annoying' 'are' 'emails' 'hate' 'is' 'learning' 'love' 'machine'
 'messages' 'powerful' 'spam']
[[1 1 0 0 0 0 0 0 1 0 1]
 [0 0 1 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 1 1 0 1 0 1 0]]



## **6. TF-IDF Vectorization**

TF‑IDF reduces the importance of common words and highlights important ones.


In [6]:

tfidf = TfidfVectorizer()

X_tfidf = tfidf.fit_transform(X_train)

print(X_tfidf.toarray())


[[0.52547275 0.52547275 0.         0.         0.         0.
  0.         0.         0.52547275 0.         0.41428875]
 [0.         0.         0.61761437 0.61761437 0.         0.
  0.         0.         0.         0.         0.48693426]
 [0.         0.         0.         0.         0.         0.52640543
  0.66767854 0.52640543 0.         0.         0.        ]
 [0.         0.         0.         0.         0.55528266 0.43779123
  0.         0.43779123 0.         0.55528266 0.        ]]



## **7. Building a Complete NLP Pipeline**


In [7]:

pipeline = Pipeline([
    ("vectorizer", TfidfVectorizer()),
    ("model", LogisticRegression())
])


## **8. Train the Pipeline**

In [8]:

pipeline.fit(X_train, y_train)


Pipeline(steps=[('vectorizer', TfidfVectorizer()),
                ('model', LogisticRegression())])

## **9. Make Predictions**

In [9]:

predictions = pipeline.predict(X_test)

print(predictions)


[1]


## **10. Model Evaluation**

In [10]:

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)


Accuracy: 1.0



## **11. Predict on New Text**


In [12]:

new_text = ["I love deep learning"]

prediction = pipeline.predict(new_text)

print(prediction)


[1]



# **Summary of NLP Pipeline**

Raw Text  
↓  
Text Cleaning  
↓  
Tokenization  
↓  
Vectorization (BoW / TF‑IDF)  
↓  
Machine Learning Model  
↓  
Prediction
