#### **Essential codes for Validation**

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv(r"data/IMDB Dataset.csv", encoding="latin1")

In [3]:
X = df['review']
y = df['sentiment']

#### **Basic Datasplit**

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#### **Train Validation and Test Split**

In [5]:
X_train, X_temp, y_train, y_temp = train_test_split(X_train, y_train, test_size=0.25, random_state=42)  #fist split
X_test, X_val, y_test, y_val = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)  #second split

#### **Stratified Train-Test Split**

In [6]:
from sklearn.model_selection import train_test_split
#For classification, especially imbalanced classification:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

#### **Startify train, validation and test Split**

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

#### **K-Fold Cross-Validation**

In [8]:
from sklearn.model_selection import KFold

kf = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

for train_index, val_index in kf.split(X):

    X_train = X.iloc[train_index]
    X_val = X.iloc[val_index]

    y_train = y.iloc[train_index]
    y_val = y.iloc[val_index]

### **Kflod with dataset**


In [9]:
import pandas as pd

data = {
    "area": [1000, 1200, 1500, 1800, 2000, 2200, 2500, 2800, 3000, 3200],
    "bedrooms": [2, 2, 3, 3, 3, 4, 4, 4, 5, 5],
    "price": [30, 35, 45, 55, 60, 70, 80, 90, 100, 110]
}

df = pd.DataFrame(data)

print(df)

   area  bedrooms  price
0  1000         2     30
1  1200         2     35
2  1500         3     45
3  1800         3     55
4  2000         3     60
5  2200         4     70
6  2500         4     80
7  2800         4     90
8  3000         5    100
9  3200         5    110


In [10]:
X = df[["area", "bedrooms"]]
y = df["price"]

In [11]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)

In [13]:
for train_index, test_index in kf.split(X):
    print(train_index)
    print(test_index)

[0 2 3 4 5 6 7 9]
[1 8]
[1 2 3 4 6 7 8 9]
[0 5]
[0 1 3 4 5 6 8 9]
[2 7]
[0 1 2 3 5 6 7 8]
[4 9]
[0 1 2 4 5 7 8 9]
[3 6]


In [14]:
X_train = X.iloc[train_index]
X_test = X.iloc[test_index]

y_train = y.iloc[train_index]
y_test = y.iloc[test_index]

In [19]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = []

for train_index, test_index in kf.split(X):

    # Split data
    X_train = X.iloc[train_index]
    X_test = X.iloc[test_index]

    y_train = y.iloc[train_index]
    y_test = y.iloc[test_index]

    # Create model
    model = LinearRegression()

    # Train
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Calculate score
    score = r2_score(y_test, y_pred)

    scores.append(score)

print("Scores:", scores)
print("Mean R2 Score:", sum(scores) / len(scores))

Scores: [0.9979866961155942, 0.9785249515102994, 0.9968648918694644, 0.9740924419757984, 0.9904775715507266]
Mean R2 Score: 0.9875893106043765


#### **Using Sklearn**

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression

model = LinearRegression()

scores = cross_val_score(model, X, y, cv=5, scoring="r2")

print("Scores:", scores)
print("Mean Score:", scores.mean())

Scores: [-3.6053648   0.8883025   0.77637251  0.88334948 -0.08057077]
Mean Score: -0.22758221646135812
[-3.6053648   0.8883025   0.77637251  0.88334948 -0.08057077]
